### ISSUE TITLE
Ruby API returns empty headers, no way to track operations

### ISSUE THREAD

**Issue by garbanotas** [Microsoft/Cognitive-SpeakerRecognition-Python#5]
Hello, MS team. Sorry for leaving Ruby related issue in Python repo, but looks like Ruby repo is not available on github. I'm able to create profiles and make enroll request successfully, but it returns empty strings in header instead of id of operation. So that I'm not able to track current status of it. I know, that call was ok, since `Get All Profiles` method returns recently created profiles with `Enrolled` status. The same issue is with Identification method (https://dev.projectoxford.ai/docs/services/563309b6778daf02acc0a508/operations/5645c523778daf217c292592). I do request and receive just empty headers. Could your team fix that for Ruby? thanks. Or also, just as suggestion, would be useful to have `/operations` GET api to return a list of current operations for subscription. Is that possible?

**Comment by momohs** [comment]
Hello @garbanotas, thanks for your comments! Can you please share with me the code snippet that you're using to parse the operation location?

**Comment by garbanotas** [comment]
@momohs thank you for reply. I use this one `https://dev.projectoxford.ai/docs/services/563309b6778daf02acc0a508/operations/5645c3271984551c84ec6797`. And I call `uri = URI('https://api.projectoxford.ai/spid/v1.0/identificationProfiles/{identificationProfileId}/enroll')` with appropriate profile id. 

response header returns  `#<Net::HTTPAccepted 202 Accepted readbody=true>`, body is empty strings - `""`. 

When I do curl request - response has header `Operation-Location: https://api.projectoxford.ai/spid/v1.0/operations/{operation_id}`

**Comment by momohs** [comment]
@garbanotas Sorry for the late reply!

I have tested out the code as is and it works fine. However, to access the operation-location from the response, you can use the line

`response.header["operation-location"]`

Please let me know if you have any further questions.

**Comment by garbanotas** [comment]
@momohs `response.header["operation-location"]` does the trick. Thank you!

**Comment by momohs** [comment]
@garbanotas That is great to know! I'll close this issue for now, please feel free to re-open if you have any further questions.
