### ISSUE TITLE
No module named http.client

### ISSUE THREAD

**Issue by nabilkhalil** [Microsoft/Cognitive-SpeakerRecognition-Python#7]
I get an error saying `No module named http.client` Sorry not really experienced with python, where can I get the http.client module?

Full error after running the command "python CreateProfile.py (my subscription key)"
`Traceback (most recent call last):
  File "CreateProfile.py", line 33, in <module>
    import IdentificationServiceHttpClientHelper
  File "/Users/Nabil/Desktop/Cognitive-SpeakerRecognition-Python/Identification/IdentificationServiceHttpClientHelper.py", line 33, in <module>
    import http.client
ImportError: No module named http.client
`

**Comment by momohs** [comment]
The module http.client was introduced in newer versions of python. Please make sure you are using python v3.4 or later.

**Comment by charity1475** [comment]
I experienced the same thing but later i discovered that i created a script with a name http.py  in my Folder which was confused with module in built script. I deleted it and things worked.

**Comment by islamtg** [comment]
I get the same issue and my Python Version is 3.8.2
